version: "3.9"
services:
  radarr:
    image: linuxserver/radarr:latest
    environment:
      - PUID=${SERVARR_PUID:-1000}
      - PGID=${SERVARR_PGID:-1000}
      - TZ=Europe/Rome
    volumes:
      - ${RADARR_CONFIG_PATH:-./data/config/radarr}:/config
      - ${RADARR_MOVIES_PATH:-./data/movies}:/movies:wr
      - ${RADARR_DOWNLOAD_PATH:-./data/download}:/downloads:wr
    ports:
      - 7878:7878
    restart: unless-stopped
    privileged: true

  sonarr:
    image: linuxserver/sonarr:latest
    environment:
      - PUID=${SERVARR_PUID:-1000}
      - PGID=${SERVARR_PGID:-1000}
      - TZ=Europe/Rome
    volumes:
      - ${SONARR_CONFIG_PATH:-./data/config/sonarr}:/config
      - ${SONARR_TV_PATH:-./data/tv}:/tv:wr
      - ${SONARR_DOWNLOAD_PATH:-./data/download}:/downloads:wr
    ports:
      - 8989:8989
    restart: unless-stopped
    privileged: true

  lidarr:
    image: linuxserver/lidarr:latest
    environment:
      - PUID=${SERVARR_PUID:-1000}
      - PGID=${SERVARR_PGID:-1000}
      - TZ=Europe/Rome
    volumes:
      - ${LIDARR_CONFIG_PATH:-./data/config/lidarr}:/config
      - ${LIDARR_MUSIC_PATH:-./data/music}:/music:wr
      - ${LIDARR_DOWNLOAD_PATH:-./data/download}:/downloads:wr
    ports:
      - 8686:8686
    restart: unless-stopped
    privileged: true

  readarr:
    image: linuxserver/readarr:nightly
    environment:
      - PUID=${SERVARR_PUID:-1000}
      - PGID=${SERVARR_PGID:-1000}
      - TZ=Europe/Rome
    volumes:
      - ${READARR_CONFIG_PATH:-./data/config/readarr}:/config
      - ${READARR_BOOK_PATH:-./data/books}:/books:wr
      - ${READARR_DOWNLOAD_PATH:-./data/download}:/downloads:wr
    ports:
      - 8787:8787
    restart: unless-stopped
    privileged: true
  
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:nightly
    environment:
      - PUID=${SERVARR_PUID:-1000}
      - PGID=${SERVARR_PGID:-1000}
      - TZ=Europe/Rome
    volumes:
      - ${PROWLARR_CONFIG_PATH:-./data/config/prowlarr}:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    privileged: true

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Rome
    ports:
      - 8191:8191
    restart: unless-stopped
    privileged: true
