version: "3.9"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=${SERVARR_PUID:-1000}
      - PGID=${SERVARR_PGID:-1000}
      - TZ=Europe/Rome
    volumes:
      - ${DATA_ROOT}${RADARR_CONFIG_PATH}/radarr:/config
      - ${DATA_ROOT}${RADARR_MOVIES_PATH}:/movies:wr
      - ${DATA_ROOT}${RADARR_DOWNLOAD_PATH}:/downloads:wr
    ports:
      - 7878:7878
    restart: unless-stopped
    privileged: true

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=${SERVARR_PUID:-1000}
      - PGID=${SERVARR_PGID:-1000}
      - TZ=Europe/Rome
    volumes:
      - ${DATA_ROOT}${SONARR_CONFIG_PATH}/sonarr:/config
      - ${DATA_ROOT}${SONARR_TV_PATH}:/tv:wr
      - ${DATA_ROOT}${SONARR_DOWNLOAD_PATH}:/downloads:wr
    ports:
      - 8989:8989
    restart: unless-stopped
    privileged: true

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    environment:
      - PUID=${SERVARR_PUID:-1000}
      - PGID=${SERVARR_PGID:-1000}
      - TZ=Europe/Rome
    volumes:
      - ${DATA_ROOT}${LIDARR_CONFIG_PATH}/lidarr:/config
      - ${DATA_ROOT}${LIDARR_MUSIC_PATH}:/music:wr
      - ${DATA_ROOT}${LIDARR_DOWNLOAD_PATH}:/downloads:wr
    ports:
      - 8686:8686
    restart: unless-stopped
    privileged: true

  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    environment:
      - PUID=${SERVARR_PUID:-1000}
      - PGID=${SERVARR_PGID:-1000}
      - TZ=Europe/Rome
    volumes:
      - ${DATA_ROOT}${READARR_CONFIG_PATH}/readarr:/config
      - ${DATA_ROOT}${READARR_BOOK_PATH}:/books:wr
      - ${DATA_ROOT}${READARR_DOWNLOAD_PATH}:/downloads:wr
    ports:
      - 8787:8787
    restart: unless-stopped
    privileged: true

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:nightly
    environment:
      - PUID=${SERVARR_PUID:-1000}
      - PGID=${SERVARR_PGID:-1000}
      - TZ=Europe/Rome
    volumes:
      - ${DATA_ROOT}${PROWLARR_CONFIG_PATH}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    privileged: true

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Rome
    ports:
      - 8191:8191
    restart: unless-stopped
    privileged: true
