version: "3.9"
services:
  radarr:
    image: linuxserver/radarr:latest
    environment:
      - PUID=501
      - PGID=500
      - TZ=Europe/Rome
    volumes:
      - ./data/config/radarr:/config
      - ./data/movies:/movies:wr
      - ./data/download:/downloads:wr
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    environment:
      - PUID=501
      - PGID=500
      - TZ=Europe/Rome
    volumes:
      - ./data/config/sonarr:/config
      - ./data/tv:/tv:wr
      - ./data/download:/downloads:wr
    ports:
      - 8989:8989
    restart: unless-stopped

  lidarr:
    image: linuxserver/lidarr:latest
    environment:
      - PUID=501
      - PGID=500
      - TZ=Europe/Rome
    volumes:
      - ./data/config/lidarr:/config
      - ./data/music:/music:wr
      - ./data/download:/downloads:wr
    ports:
      - 8686:8686
    restart: unless-stopped

  readarr:
    image: linuxserver/readarr:nightly
    environment:
      - PUID=501
      - PGID=500
      - TZ=Europe/Rome
    volumes:
      - ./data/config/readarr:/config
      - ./data/books:/books:wr
      - ./data/download:/downloads:wr
    ports:
      - 8787:8787
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    environment:
      - PUID=501
      - PGID=500
      - TZ=Europe/Rome
      - AUTO_UPDATE=true
    volumes:
      - ./data/config/jackett:/config
      - ./data/download:/downloads:wr
    ports:
      - 9117:9117
    restart: unless-stopped
  
